export const UPDATE_SELECTED_COUNTRY = "UPDATE_SELECTED_COUNTRY";
export const UPDATE_LINE_DATA_TYPE = "UPDATE_LINE_DATA_TYPE";
export const UPDATE_RANKED_DATA_TYPE = "UPDATE_RANKED_DATA_TYPE";
export const UPDATE_CURRENT_TAB = "UPDATE_CURRENT_TAB";
export const UPDATE_RANGE_LENGTH = "UPDATE_RANGE_LENGTH";