export const countries = [
  { code: "AND", flag: "AD", label: "Andorra", phone: "376" },
  {
    code: "ARE",
    flag: "AE",
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AFG", flag: "AF", label: "Afghanistan", phone: "93" },
  {
    code: "ATG",
    flag: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AIA", flag: "AI", label: "Anguilla", phone: "1-264" },
  { code: "ALB", flag: "AL", label: "Albania", phone: "355" },
  { code: "ARM", flag: "AM", label: "Armenia", phone: "374" },
  { code: "ARG", flag: "AR", label: "Argentina", phone: "54" },
  { code: "AUT", flag: "AT", label: "Austria", phone: "43" },
  {
    code: "AUS",
    flag: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AZE", flag: "AZ", label: "Azerbaijan", phone: "994" },
  {
    code: "BIH",
    flag: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BGD", flag: "BD", label: "Bangladesh", phone: "880" },
  { code: "BEL", flag: "BE", label: "Belgium", phone: "32" },
  { code: "BGR", flag: "BG", label: "Bulgaria", phone: "359" },
  { code: "BHR", flag: "BH", label: "Bahrain", phone: "973" },
  { code: "BOL", flag: "BO", label: "Bolivia", phone: "591" },
  { code: "BRA", flag: "BR", label: "Brazil", phone: "55" },
  { code: "BLR", flag: "BY", label: "Belarus", phone: "375" },
  {
    code: "CAN",
    flag: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  { code: "CHE", flag: "CH", label: "Switzerland", phone: "41" },
  { code: "CHL", flag: "CL", label: "Chile", phone: "56" },
  { code: "CHN", flag: "CN", label: "China", phone: "86" },
  { code: "COL", flag: "CO", label: "Colombia", phone: "57" },
  { code: "CRI", flag: "CR", label: "Costa Rica", phone: "506" },
  { code: "CUB", flag: "CU", label: "Cuba", phone: "53" },
  { code: "CYP", flag: "CY", label: "Cyprus", phone: "357" },
  { code: "CZE", flag: "CZ", label: "Czech Republic", phone: "420" },
  {
    code: "DEU",
    flag: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "DNK", flag: "DK", label: "Denmark", phone: "45" },
  { code: "DMA", flag: "DM", label: "Dominica", phone: "1-767" },
  {
    code: "DOM",
    flag: "DO",
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZA", flag: "DZ", label: "Algeria", phone: "213" },
  { code: "EST", flag: "EE", label: "Estonia", phone: "372" },
  { code: "EGY", flag: "EG", label: "Egypt", phone: "20" },
  { code: "ESP", flag: "ES", label: "Spain", phone: "34" },
  { code: "FIN", flag: "FI", label: "Finland", phone: "358" },
  { code: "FJI", flag: "FJ", label: "Fiji", phone: "679" },
  {
    code: "FRA",
    flag: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GBR", flag: "GB", label: "United Kingdom", phone: "44" },
  { code: "GEO", flag: "GE", label: "Georgia", phone: "995" },
  { code: "GRC", flag: "GR", label: "Greece", phone: "30" },
  { code: "HKG", flag: "HK", label: "Hong Kong", phone: "852" },
  { code: "HRV", flag: "HR", label: "Croatia", phone: "385" },
  { code: "HUN", flag: "HU", label: "Hungary", phone: "36" },
  { code: "IDN", flag: "ID", label: "Indonesia", phone: "62" },
  { code: "IRL", flag: "IE", label: "Ireland", phone: "353" },
  { code: "ISR", flag: "IL", label: "Israel", phone: "972" },
  { code: "IND", flag: "IN", label: "India", phone: "91" },
  { code: "IRQ", flag: "IQ", label: "Iraq", phone: "964" },
  {
    code: "IRN",
    flag: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "ISL", flag: "IS", label: "Iceland", phone: "354" },
  { code: "ITA", flag: "IT", label: "Italy", phone: "39" },
  { code: "JAM", flag: "JM", label: "Jamaica", phone: "1-876" },
  {
    code: "JPN",
    flag: "JP",
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  {
    code: "PRK",
    flag: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  { code: "KOR", flag: "KR", label: "Korea, Republic of", phone: "82" },
  { code: "KWT", flag: "KW", label: "Kuwait", phone: "965" },
  { code: "KAZ", flag: "KZ", label: "Kazakhstan", phone: "7" },
  { code: "LTU", flag: "LT", label: "Lithuania", phone: "370" },
  { code: "LUX", flag: "LU", label: "Luxembourg", phone: "352" },
  { code: "LVA", flag: "LV", label: "Latvia", phone: "371" },
  { code: "MLT", flag: "MT", label: "Malta", phone: "356" },
  { code: "MEX", flag: "MX", label: "Mexico", phone: "52" },
  { code: "MYS", flag: "MY", label: "Malaysia", phone: "60" },
  { code: "NLD", flag: "NL", label: "Netherlands", phone: "31" },
  { code: "NOR", flag: "NO", label: "Norway", phone: "47" },
  { code: "NZL", flag: "NZ", label: "New Zealand", phone: "64" },
  { code: "PAN", flag: "PA", label: "Panama", phone: "507" },
  { code: "PER", flag: "PE", label: "Peru", phone: "51" },
  { code: "PHL", flag: "PH", label: "Philippines", phone: "63" },
  { code: "PAK", flag: "PK", label: "Pakistan", phone: "92" },
  { code: "POL", flag: "PL", label: "Poland", phone: "48" },
  { code: "PRT", flag: "PT", label: "Portugal", phone: "351" },
  { code: "QAT", flag: "QA", label: "Qatar", phone: "974" },
  { code: "ROU", flag: "RO", label: "Romania", phone: "40" },
  { code: "SRB", flag: "RS", label: "Serbia", phone: "381" },
  { code: "RUS", flag: "RU", label: "Russian Federation", phone: "7" },
  { code: "SAU", flag: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "SDN", flag: "SD", label: "Sudan", phone: "249" },
  { code: "SWE", flag: "SE", label: "Sweden", phone: "46" },
  { code: "SGP", flag: "SG", label: "Singapore", phone: "65" },
  { code: "SVK", flag: "SK", label: "Slovakia", phone: "421" },
  {
    code: "SYR",
    flag: "SY",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "TKM", flag: "TM", label: "Turkmenistan", phone: "993" },
  { code: "TUN", flag: "TN", label: "Tunisia", phone: "216" },
  { code: "TON", flag: "TO", label: "Tonga", phone: "676" },
  { code: "TUR", flag: "TR", label: "Turkey", phone: "90" },
  { code: "UKR", flag: "UA", label: "Ukraine", phone: "380" },
  {
    code: "USA",
    flag: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
  { code: "VNM", flag: "VN", label: "Vietnam", phone: "84" },
  { code: "ZAF", flag: "ZA", label: "South Africa", phone: "27" },
];
